"""stackmind decisions — Audit-trail decision entries (PLAT-04).

Any state mutation that affects canonical files (``runtime/boot/<agent>.yaml``,
``runtime/TREE.yaml``) should be traceable in ``decisions/``. PLAT-04 adds a
lightweight ``NORMALIZATION`` decision type that is auto-generated by the
tooling whenever it modifies a canonical file — so normalization actions no
longer bypass the audit trail.
"""

import re
from datetime import datetime, timezone
from pathlib import Path

import yaml

_DECISION_ID_PATTERN = re.compile(r"D-(\d+)")


def decisions_dir(sync_path: Path) -> Path:
    return sync_path / "decisions"


def next_decision_id(sync_path: Path) -> str:
    """Return the next sequential decision id (e.g. ``D-001``).

    Scans existing ``decisions/`` filenames for ``D-<NNN>`` and returns one
    greater than the highest found.
    """
    d = decisions_dir(sync_path)
    highest = 0
    if d.is_dir():
        for entry in d.iterdir():
            match = _DECISION_ID_PATTERN.search(entry.name)
            if match:
                highest = max(highest, int(match.group(1)))
    return f"D-{highest + 1:03d}"


def write_normalization_decision(
    sync_path: Path,
    authored_by: str,
    changes: list[dict],
    reason: str,
    session: int | str | None = None,
) -> Path:
    """Write an auto-generated NORMALIZATION decision entry.

    Args:
        sync_path: Path to the .sync/ runtime directory.
        authored_by: Agent credited with the normalization (e.g. ``claude``).
        changes: List of change records (each describing a canonical file and
            its from/to values).
        reason: Human-readable reason for the normalization.
        session: Optional session identifier.

    Returns:
        Path to the written decision file.
    """
    d = decisions_dir(sync_path)
    d.mkdir(parents=True, exist_ok=True)

    decision_id = next_decision_id(sync_path)
    data = {
        "id": decision_id,
        "type": "NORMALIZATION",
        "authored_by": authored_by,
        "session": session,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "changes": changes,
        "reason": reason,
    }

    dest = d / f"{decision_id}-normalization.yaml"
    dest.write_text(
        yaml.dump(data, default_flow_style=False, sort_keys=False),
        encoding="utf-8",
    )
    return dest


def build_canonical_change(
    file_rel: str,
    previous: dict | None,
    current: dict | None,
    fields: tuple[str, ...] = ("session_count", "tree_version", "graph_version", "release"),
) -> dict:
    """Build a change record describing how a canonical file's fields changed."""
    prev, curr = previous or {}, current or {}
    diffs = {
        f"{field}_{suffix}": val
        for field in fields
        if (old := prev.get(field)) != (new := curr.get(field))
        for suffix, val in (("from", old), ("to", new))
    }
    return {"file": file_rel, **diffs}
