"""StackMind Autonomous Delivery TUI package."""

from .app import (
    create_tui_adapter,
    dispatch_delivery_command,
    render_activity_stream,
    render_completion_surface,
    render_operation_tree,
    render_phase_banner,
    render_plan_surface,
    render_project_delivery_view,
    render_roles_panel,
    render_work_orders_panel,
    tui,
)
from .chat import (
    render_assistant_message,
    render_assistant_message_str,
    render_chat_transcript,
    render_chat_transcript_str,
    render_user_message,
    render_user_message_str,
)
from .diff import (
    parse_unified_diff,
    render_file_diff,
    render_unified_diff,
    render_unified_diff_str,
)
from .events import (
    OperationalEventManager,
    ToolActivity,
    ToolStatus,
    extract_assistant_response,
    render_operational_event,
    render_operational_event_str,
    render_tool_activity,
    render_tool_activity_line,
    render_tool_activity_line_str,
    render_tool_activity_str,
)
from .governance import (
    VERIFICATION_DIMENSIONS,
    render_contract_hud,
    render_contract_hud_str,
    render_plan_panel,
    render_plan_panel_str,
    render_verification_matrix,
    render_verification_matrix_str,
)
from .landing import (
    render_landing_block,
    render_landing_block_str,
)
from .state import (
    ActivityEntry,
    AutonomousDeliveryState,
    ChatMessage,
    OperationNode,
    PlanRevision,
    ProjectPhase,
    RoleStatus,
    WorkOrderItem,
)

__all__ = [
    "ActivityEntry",
    "AutonomousDeliveryState",
    "ChatMessage",
    "OperationNode",
    "OperationalEventManager",
    "PlanRevision",
    "ProjectPhase",
    "RoleStatus",
    "ToolActivity",
    "ToolStatus",
    "VERIFICATION_DIMENSIONS",
    "WorkOrderItem",
    "create_tui_adapter",
    "dispatch_delivery_command",
    "extract_assistant_response",
    "parse_unified_diff",
    "render_activity_stream",
    "render_assistant_message",
    "render_assistant_message_str",
    "render_chat_transcript",
    "render_chat_transcript_str",
    "render_completion_surface",
    "render_contract_hud",
    "render_contract_hud_str",
    "render_file_diff",
    "render_landing_block",
    "render_landing_block_str",
    "render_operation_tree",
    "render_operational_event",
    "render_operational_event_str",
    "render_phase_banner",
    "render_plan_panel",
    "render_plan_panel_str",
    "render_plan_surface",
    "render_project_delivery_view",
    "render_roles_panel",
    "render_tool_activity",
    "render_tool_activity_line",
    "render_tool_activity_line_str",
    "render_tool_activity_str",
    "render_unified_diff",
    "render_unified_diff_str",
    "render_user_message",
    "render_user_message_str",
    "render_verification_matrix",
    "render_verification_matrix_str",
    "render_work_orders_panel",
    "tui",
]
